### ISSUE TITLE
jQuery.browser is deprecated 

### ISSUE THREAD

**Issue by jkancio** [pupunzi/jquery.mb.menu#16]
If you use jQuery above or equal to version 1.9 we must adopt "Migrate older jQuery code to jQuery 1.9+" (https://github.com/jquery/jquery-migrate/)

**Comment by goofy810** [comment]
This is still an issue, Are there plans to fix it ?

**Comment by pupunzi** [comment]
That is not an issue as the plugin is working fine since the latest jQuery library. It's using the jquery.mb.browser plugin and it doesn't need the jquery-migrate plugin.
If you try including the latest jQuery (2.2.4) you'll see :-)
